import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist", "**/vite.config.ts", "**/vitest.config.ts", "**/*.config.js", "**/*.config.ts", "node_modules", "coverage", "**/*.d.ts", "src/test", "**/*.test.*", "**/*.spec.*", "**/AdvancedTechnicalAnalysis.tsx", "**/BitcoinQRCodeDialog.tsx", "**/ConversionSimulator.tsx", "**/AutoFocusInput.tsx", "**/BackupStatsTab.tsx", "**/InventarioHistoricoComparacao.tsx", "**/EstoqueAnalisePedidos.tsx", "**/EvolucoesTimeline.tsx", "**/GlobalSearch.tsx", "**/SangriaInteligente.tsx", "**/DataTable.tsx", "**/PatientSelector.tsx", "**/ADRsPage.tsx", "**/SystemLogsPage.tsx", "**/BarcodeScannerDialog.tsx", "**/PermissoesManager.tsx", "**/useOdontogramaStore.ts", "**/OnboardingWizard.tsx", "**/useFocusMode.ts", "**/EstoqueAnaliseConsumo.tsx", "**/ContasPagar.tsx", "**/NotasFiscais.tsx", "**/Odontograma2D.tsx", "**/ProntuarioPDF.tsx", "**/ReceitaForm.tsx", "**/error-boundary/index.tsx"] },
  {
    extends: [js.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parser: tseslint.parser,
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-hooks/react-compiler": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/purity": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/no-component-during-render": "off",
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Regras essenciais apenas
      "@typescript-eslint/no-unused-vars": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      // Desabilitar TODAS as regras de tipo
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/no-misused-promises": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/await-thenable": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-unary-minus": "off",
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unnecessary-type-arguments": "off",
      "@typescript-eslint/no-unnecessary-type-constraint": "off",
      "@typescript-eslint/no-unnecessary-qualifier": "off",
      "@typescript-eslint/no-unnecessary-template-literal": "off",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-duplicate-enum-values": "off",
      "@typescript-eslint/no-base-to-string": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-meaningless-void-operator": "off",
      "@typescript-eslint/no-misused-spread": "off",
      "@typescript-eslint/no-deprecated": "off",
      "@typescript-eslint/no-use-before-define": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/restrict-plus-operands": "off",
      "@typescript-eslint/unbound-method": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/prefer-optional-chain": "off",
      "@typescript-eslint/prefer-as-const": "off",
      "@typescript-eslint/prefer-readonly": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
      "@typescript-eslint/prefer-return-this-type": "off",
      "@typescript-eslint/prefer-string-starts-ends-with": "off",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/require-array-sort-compare": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
      "@typescript-eslint/return-await": "off",
      "@typescript-eslint/prefer-promise-reject-errors": "off",
      "@typescript-eslint/only-throw-error": "off",
      "@typescript-eslint/prefer-find": "off",
      "@typescript-eslint/prefer-includes": "off",
      "@typescript-eslint/prefer-for-of": "off",
      "@typescript-eslint/no-array-constructor": "off",
      "@typescript-eslint/no-empty-interface": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "@typescript-eslint/no-namespace": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-var-requires": "off",
      "@typescript-eslint/triple-slash-reference": "off",
      "@typescript-eslint/typedef": "off",
      // Regras de plugins externos
      "preserve-caught-error": "off",
      "no-undef": "off",
      "@typescript-eslint/no-use-before-define": "off",
      "no-use-before-define": "off",
      "no-redeclare": "off",
      "@typescript-eslint/no-redeclare": "off",
    },
  },
);
