export interface CatalogModule {
  id: number;
  module_key: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  subscribed: boolean;
  is_active: boolean;
  dependencies: string[];
}

export const MODULE_CATALOG: readonly CatalogModule[] = Object.freeze([
  {
    id: 1,
    module_key: "DASHBOARD",
    name: "Dashboard",
    description: "Painel principal com KPIs e metricas",
    category: "CORE",
    icon: "LayoutDashboard",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 2,
    module_key: "AGENDA",
    name: "Agenda",
    description: "Agendamento de consultas e procedimentos",
    category: "CORE",
    icon: "CalendarDays",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 3,
    module_key: "PACIENTES",
    name: "Pacientes",
    description: "Gestao de pacientes e prontuarios",
    category: "CORE",
    icon: "Users",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 4,
    module_key: "PEP",
    name: "Prontuario Eletronico",
    description: "Prontuario eletronico do paciente",
    category: "CORE",
    icon: "FileHeart",
    subscribed: true,
    is_active: true,
    dependencies: ["PACIENTES"],
  },
  {
    id: 5,
    module_key: "FINANCEIRO",
    name: "Financeiro",
    description: "Gestao financeira e contas",
    category: "FINANCEIRO",
    icon: "PieChart",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 6,
    module_key: "PDV",
    name: "Ponto de Venda",
    description: "Ponto de venda e cobrancas",
    category: "FINANCEIRO",
    icon: "BarChart3",
    subscribed: true,
    is_active: true,
    dependencies: ["FINANCEIRO"],
  },
  {
    id: 7,
    module_key: "FISCAL",
    name: "Fiscal",
    description: "Emissao de notas fiscais",
    category: "FINANCEIRO",
    icon: "FileText",
    subscribed: true,
    is_active: true,
    dependencies: ["FINANCEIRO"],
  },
  {
    id: 8,
    module_key: "ESTOQUE",
    name: "Estoque",
    description: "Controle de materiais e insumos",
    category: "OPERACIONAL",
    icon: "Package",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 9,
    module_key: "INVENTARIO",
    name: "Inventario",
    description: "Inventario e contagem de estoque",
    category: "OPERACIONAL",
    icon: "Clipboard",
    subscribed: true,
    is_active: true,
    dependencies: ["ESTOQUE"],
  },
  {
    id: 10,
    module_key: "CRM",
    name: "CRM",
    description: "Gestao de leads e funil de vendas",
    category: "COMERCIAL",
    icon: "Target",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 11,
    module_key: "FIDELIDADE",
    name: "Fidelidade",
    description: "Programa de fidelidade e pontos",
    category: "COMERCIAL",
    icon: "Send",
    subscribed: true,
    is_active: true,
    dependencies: ["PACIENTES"],
  },
  {
    id: 12,
    module_key: "CRYPTO_PAYMENTS",
    name: "Pagamentos Crypto",
    description: "Pagamentos em criptomoedas",
    category: "FINANCEIRO",
    icon: "Bitcoin",
    subscribed: true,
    is_active: true,
    dependencies: ["FINANCEIRO"],
  },
  {
    id: 13,
    module_key: "TELEODONTO",
    name: "Teleodonto",
    description: "Teleconsulta odontologica",
    category: "CLINICO",
    icon: "Video",
    subscribed: true,
    is_active: true,
    dependencies: ["PACIENTES", "AGENDA"],
  },
  {
    id: 14,
    module_key: "TISS",
    name: "TISS",
    description: "Integracao com convenios via TISS",
    category: "CLINICO",
    icon: "FileSpreadsheet",
    subscribed: true,
    is_active: true,
    dependencies: ["PACIENTES"],
  },
  {
    id: 15,
    module_key: "BI",
    name: "Business Intelligence",
    description: "Relatorios avancados e BI",
    category: "ADMINISTRATIVO",
    icon: "BarChart3",
    subscribed: true,
    is_active: true,
    dependencies: ["DASHBOARD"],
  },
  {
    id: 16,
    module_key: "LGPD",
    name: "LGPD",
    description: "Conformidade com Lei Geral de Protecao de Dados",
    category: "ADMINISTRATIVO",
    icon: "ShieldCheck",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 17,
    module_key: "DENTISTAS",
    name: "Dentistas",
    description: "Gestao de dentistas e especialistas",
    category: "CLINICO",
    icon: "Stethoscope",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
  {
    id: 18,
    module_key: "FUNCIONARIOS",
    name: "Funcionarios",
    description: "Gestao de funcionarios e equipe",
    category: "ADMINISTRATIVO",
    icon: "Users",
    subscribed: true,
    is_active: true,
    dependencies: [],
  },
]);
