// cspell:disable
import {
  Settings,
  LayoutDashboard,
  Users,
  UserPlus,
  Briefcase,
  Calendar,
  ClipboardList,
  FileText,
  Stethoscope,
  Package,
  DollarSign,
  CreditCard,
  TrendingUp,
  Activity,
  Shield,
  PenTool,
  Video,
  Bot,
  FileBarChart,
} from "lucide-react";

export const moduleIcons: Record<string, unknown> = {
  DASHBOARD: LayoutDashboard,
  PACIENTES: Users,
  DENTISTAS: UserPlus,
  FUNCIONARIOS: Briefcase,
  AGENDA: Calendar,
  PROCEDIMENTOS: ClipboardList,
  PEP: FileText,
  ODONTOGRAMA: Stethoscope,
  ESTOQUE: Package,
  FINANCEIRO: DollarSign,
  SPLIT_PAGAMENTO: CreditCard,
  INADIMPLENCIA: TrendingUp,
  COBRANCA: CreditCard,
  CRM: Activity,
  MARKETING_AUTO: TrendingUp,
  BI: FileBarChart,
  LGPD: Shield,
  ASSINATURA_ICP: PenTool,
  TISS: FileText,
  TELEODONTO: Video,
  FLUXO_DIGITAL: Activity,
  IA: Bot,
  RELATORIOS: FileBarChart,
  ORCAMENTOS: DollarSign,
};
