import {
  LayoutDashboard,
  Users,
  UserPlus,
  Calendar,
  Stethoscope,
  FileText,
  DollarSign,
  TrendingUp,
  ClipboardList,
  Shield,
  Activity,
  Package,
  CreditCard,
  FileBarChart,
  Briefcase,
  FileSignature,
  Bitcoin,
  ShoppingCart,
  Receipt,
  ClipboardCheck,
  Gift,
  UserCircle,
  Database,
  HardDrive,
  Github,
  Terminal,
} from "lucide-react";

export const MODULE_ICONS: Record<
  string,
  React.ComponentType<{ className?: string }>
> = {
  DASHBOARD: LayoutDashboard,
  PACIENTES: Users,
  DENTISTAS: UserPlus,
  FUNCIONARIOS: Briefcase,
  AGENDA: Calendar,
  PROCEDIMENTOS: ClipboardList,
  PEP: FileText,
  ODONTOGRAMA: Stethoscope,
  CONTRATOS: FileSignature,
  ESTOQUE: Package,
  INVENTARIO: ClipboardCheck,
  FINANCEIRO: DollarSign,
  SPLIT_PAGAMENTO: CreditCard,
  CRYPTO_PAYMENTS: Bitcoin,
  PDV: ShoppingCart,
  FISCAL: Receipt,
  INADIMPLENCIA: TrendingUp,
  COBRANCA: CreditCard,
  CRM: Activity,
  FIDELIDADE: Gift,
  PORTAL_PACIENTE: UserCircle,
  MARKETING_AUTO: TrendingUp,
  BI: FileBarChart,
  LGPD: Shield,
  ASSINATURA_ICP: FileText,
  TISS: FileText,
  TELEODONTO: Activity,
  FLUXO_DIGITAL: Activity,
  IA: Activity,
  RELATORIOS: FileBarChart,
  ORCAMENTOS: DollarSign,
  DATABASE_ADMIN: Database,
  BACKUPS: HardDrive,
  GITHUB_TOOLS: Github,
  TERMINAL: Terminal,
};
