// Mapeamento de rotas para labels legíveis
export const ROUTE_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  pacientes: "Pacientes",
  dentistas: "Dentistas",
  funcionarios: "Funcionários",
  agenda: "Agenda",
  procedimentos: "Procedimentos",
  pep: "Prontuário (PEP)",
  financeiro: "Financeiro",
  transacoes: "Transações",
  "contas-receber": "Contas a Receber",
  "contas-pagar": "Contas a Pagar",
  "notas-fiscais": "Notas Fiscais",
  "crypto-pagamentos": "Pagamentos Cripto",
  orcamentos: "Orçamentos",
  contratos: "Contratos",
  crm: "CRM",
  "crm-funil": "CRM",
  cobranca: "Cobrança",
  "split-pagamento": "Split de Pagamento",
  fidelidade: "Programa de Fidelidade",
  bi: "Business Intelligence",
  lgpd: "LGPD - Conformidade",
  "assinatura-digital": "Assinatura Digital ICP-Brasil",
  "marketing-auto": "Automação de Marketing",
  inadimplencia: "Inadimplência",
  relatorios: "Relatórios",
  "lgpd-compliance": "Compliance LGPD",
  teleodontologia: "Teleodontologia",
  historico: "Histórico de Consultas",
  "ia-radiografia": "IA para Radiografia",
  "portal-paciente": "Portal do Paciente",
  configuracoes: "Configurações",
  modulos: "Gestão de Módulos",
  "audit-logs": "Logs de Auditoria",
  estoque: "Estoque",
  cadastros: "Cadastros",
  movimentacoes: "Movimentações",
  pedidos: "Pedidos",
  requisicoes: "Requisições",
  "analise-consumo": "Análise de Consumo",
  "analise-pedidos": "Análise de Pedidos",
  integracoes: "Integrações",
};
